export const menuData = [
  {
    category: "🥟 Pastéis",
    items: [
      {
        id: "pastel-1",
        name: "Pastel de Carne",
        description: "Pastel crocante recheado com carne moída temperada, cebola e azeitonas",
        price: 8.5,
        image: "/pastel-de-carne-brasileiro.jpg",
      },
      {
        id: "pastel-2",
        name: "Pastel de Queijo",
        description: "Massa crocante com muito queijo mussarela derretido",
        price: 7.5,
        image: "/pastel-de-queijo-brasileiro.jpg",
      },
      {
        id: "pastel-3",
        name: "Pastel de Frango",
        description: "Recheio cremoso de frango desfiado com catupiry",
        price: 9.0,
        image: "/pastel-de-frango-catupiry.jpg",
      },
      {
        id: "pastel-4",
        name: "Pastel de Pizza",
        description: "Recheado com mussarela, presunto, tomate e orégano",
        price: 9.5,
        image: "/pizza-cake.png",
      },
      {
        id: "pastel-5",
        name: "Pastel de Palmito",
        description: "Palmito com queijo e temperos especiais",
        price: 10.0,
        image: "/pastel-de-palmito.png",
      },
      {
        id: "pastel-6",
        name: "Pastel de Camarão",
        description: "Camarões selecionados com catupiry e ervas",
        price: 14.0,
        image: "/pastel-de-camar-o.jpg",
      },
    ],
  },
  {
    category: "🥤 Sucos Naturais",
    items: [
      {
        id: "suco-1",
        name: "Suco de Laranja",
        description: "Laranja natural espremida na hora, refrescante e vitamínico",
        price: 6.0,
        image: "/natural-orange-juice.png",
      },
      {
        id: "suco-2",
        name: "Suco de Limão",
        description: "Limonada natural feita na hora, perfeita para o calor",
        price: 5.5,
        image: "/suco-de-lim-o-natural.jpg",
      },
      {
        id: "suco-3",
        name: "Suco de Morango",
        description: "Morangos frescos batidos com leite e açúcar",
        price: 8.0,
        image: "/suco-de-morango.jpg",
      },
      {
        id: "suco-4",
        name: "Suco de Abacaxi",
        description: "Abacaxi fresco batido com hortelã",
        price: 7.0,
        image: "/suco-de-abacaxi-hortel-.jpg",
      },
      {
        id: "suco-5",
        name: "Suco de Maracujá",
        description: "Maracujá puro, refrescante e levemente adocicado",
        price: 7.5,
        image: "/suco-de-maracuj-.jpg",
      },
      {
        id: "suco-6",
        name: "Suco de Açaí",
        description: "Açaí batido com banana e guaraná, energizante natural",
        price: 9.5,
        image: "/suco-de-a-a--banana.jpg",
      },
    ],
  },
  {
    category: "🥤 Refrigerantes",
    items: [
      {
        id: "refri-1",
        name: "Coca-Cola Lata",
        description: "Refrigerante de cola gelado, 350ml",
        price: 5.0,
        image: "/coca-cola-lata.jpg",
      },
      {
        id: "refri-2",
        name: "Guaraná Antarctica Lata",
        description: "Guaraná brasileiro gelado, 350ml",
        price: 5.0,
        image: "/guaran--antarctica-lata.jpg",
      },
      {
        id: "refri-3",
        name: "Fanta Laranja Lata",
        description: "Refrigerante sabor laranja, 350ml",
        price: 5.0,
        image: "/fanta-laranja-lata.jpg",
      },
      {
        id: "refri-4",
        name: "Sprite Lata",
        description: "Refrigerante de limão gelado, 350ml",
        price: 5.0,
        image: "/sprite-lata.jpg",
      },
      {
        id: "refri-5",
        name: "Coca-Cola 2L",
        description: "Refrigerante de cola, garrafa 2 litros",
        price: 10.0,
        image: "/coca-cola-2-litros.jpg",
      },
      {
        id: "refri-6",
        name: "Guaraná Antarctica 2L",
        description: "Guaraná brasileiro, garrafa 2 litros",
        price: 10.0,
        image: "/guaran--antarctica-2-litros.jpg",
      },
    ],
  },
]
